### ISSUE TITLE
Post-session: index those who did not participate

### ISSUE THREAD

**Issue by jesswinssinger** [hmc-room-draw/room-draw#31] opened 2017-10-06 19:52 UTC
https://docs.google.com/document/d/1OOfGVs4Fb2Yk5RXqzVkv199xiUvUxQKvgIwjh5IvsyI/edit

**Comment by jesswinssinger** [comment] 2017-10-19 21:15
@g-rocket Why is this blocked?

**Comment by g-rocket** [comment] 2017-10-20 02:09
@jesswinssinger As far as I'm aware, we don't have any where near the database features needed to implement this.  If that's not the case, feel free to unblock it.

**Comment by jesswinssinger** [comment] 2017-10-20 02:11
@g-rocket What do you mean? There's a "has_participated" boolean for students

**Comment by g-rocket** [comment] 2017-10-20 02:12
@jesswinssinger Then I guess the database features have been added; awesome!

**Comment by g-rocket** [comment] 2017-10-23 04:22
Duplicate of #63

**Closed by g-rocket** 2017-10-23 04:22 UTC
Labels: admin, admin section 2
